name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/andyruwruw/WaterBot
        azure-pipeline-name: 'andyruwruw.stardew-valley-water-bot'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}